'use strict';

const authRoutes = require('./authRoutes');
const ingredientRoutes = require('./ingredientRoutes');
const purchaseRoutes = require('./purchaseRoutes');
const productRoutes = require('./productRoutes');
const productionRoutes = require('./productionRoutes');
const saleRoutes = require('./saleRoutes');
const centerRoutes = require('./centerRoutes');
const deliveryRoutes = require('./deliveryRoutes');
const settlementRoutes = require('./settlementRoutes');
const wasteRoutes = require('./wasteRoutes');
const offerRoutes = require('./offerRoutes');
const orderRoutes = require('./orderRoutes');
const cashRoutes = require('./cashRoutes');
const reportRoutes = require('./reportRoutes');
const closingRoutes = require('./closingRoutes');
const settingsRoutes     = require('./settingsRoutes');
const financeRoutes      = require('./financeRoutes');
const siteSettingsRoutes = require('./siteSettingsRoutes');
const uploadRoutes       = require('./uploadRoutes');
const nutritionRoutes    = require('./nutritionRoutes');
const reviewRoutes       = require('./reviewRoutes');
const employeeRoutes     = require('./employeeRoutes');
const salaryRoutes       = require('./salaryRoutes');
const advanceRoutes        = require('./advanceRoutes');
const centerPortalRoutes   = require('./centerPortalRoutes');
const setupRoutes          = require('./setupRoutes');
const userRoutes           = require('./userRoutes');
const attendanceRoutes     = require('./attendanceRoutes');
const internalOrderRoutes  = require('./internalOrderRoutes');
const printerRoutes        = require('./printerRoutes');
const profitShareRoutes    = require('./profitShareRoutes');
const americansPortalRoutes = require('./americansPortalRoutes');
const shiftRoutes = require('./shiftRoutes');

module.exports = function mountRoutes(app) {
  app.use('/api/auth', authRoutes);
  app.use('/api/ingredients', ingredientRoutes);
  app.use('/api/purchases', purchaseRoutes);
  app.use('/api/products', productRoutes);
  app.use('/api/production-batches', productionRoutes);
  app.use('/api/sales', saleRoutes);
  app.use('/api/centers', centerRoutes);
  app.use('/api/center-deliveries', deliveryRoutes);
  app.use('/api/center-settlements', settlementRoutes);
  app.use('/api/waste', wasteRoutes);
  app.use('/api/offers', offerRoutes);
  app.use('/api/orders', orderRoutes);
  app.use('/api/cash', cashRoutes);
  app.use('/api/reports', reportRoutes);
  app.use('/api/daily-closing', closingRoutes);
  app.use('/api/settings',      settingsRoutes);
  app.use('/api/finance',       financeRoutes);
  app.use('/api/site-settings', siteSettingsRoutes);
  app.use('/api/upload',        uploadRoutes);
  app.use('/api/nutrition',     nutritionRoutes);
  app.use('/api/reviews',       reviewRoutes);
  app.use('/api/employees',     employeeRoutes);
  app.use('/api/salary',        salaryRoutes);
  app.use('/api/advances',      advanceRoutes);
  app.use('/api/center-portal', centerPortalRoutes);
  app.use('/api/setup',        setupRoutes);
  app.use('/api/users',        userRoutes);
  app.use('/api/attendance',   attendanceRoutes);
  app.use('/api/internal-orders', internalOrderRoutes);
  app.use('/api/printer', printerRoutes);
  app.use('/api/profit-shares', profitShareRoutes);
  app.use('/api/americans-portal', americansPortalRoutes);
  app.use('/api/shifts', shiftRoutes);
};
